INSERT INTO [dbo].[Cars] ([CarId], [BrandId], [ColorId], [CarName], [DailyPrice], [ModelYear], [Description]) VALUES (1, 1, 1, N'Audi A3', CAST(250 AS Decimal(18, 0)), 2010, N'Benzinli, Yarı Otomatik,')
INSERT INTO [dbo].[Cars] ([CarId], [BrandId], [ColorId], [CarName], [DailyPrice], [ModelYear], [Description]) VALUES (2, 2, 2, N'Renault Megane', CAST(200 AS Decimal(18, 0)), 2021, N'Dizel, Otomatik')
INSERT INTO [dbo].[Cars] ([CarId], [BrandId], [ColorId], [CarName], [DailyPrice], [ModelYear], [Description]) VALUES (3, 3, 3, N'Volkswagen Passat', CAST(220 AS Decimal(18, 0)), 2018, N'Dizel, Otomatik')
INSERT INTO [dbo].[Cars] ([CarId], [BrandId], [ColorId], [CarName], [DailyPrice], [ModelYear], [Description]) VALUES (4, 2, 3, N'Renault Clio', CAST(125 AS Decimal(18, 0)), 2017, N'Dizel, Manuel')
INSERT INTO [dbo].[Cars] ([CarId], [BrandId], [ColorId], [CarName], [DailyPrice], [ModelYear], [Description]) VALUES (5, 4, 2, N'Fiat Doblo', CAST(110 AS Decimal(18, 0)), 2017, N'Dizel, Manuel')
INSERT INTO [dbo].[Cars] ([CarId], [BrandId], [ColorId], [CarName], [DailyPrice], [ModelYear], [Description]) VALUES (6, 2, 4, N'Renault Clio', CAST(120 AS Decimal(18, 0)), 2020, N'Dizel, Manuel')
INSERT INTO [dbo].[Cars] ([CarId], [BrandId], [ColorId], [CarName], [DailyPrice], [ModelYear], [Description]) VALUES (7, 5, 3, N'BMW 5.20', CAST(500 AS Decimal(18, 0)), 2012, N'Dizel, Otomatik')
INSERT INTO [dbo].[Cars] ([CarId], [BrandId], [ColorId], [CarName], [DailyPrice], [ModelYear], [Description]) VALUES (8, 6, 4, N'Mercedes C200D', CAST(330 AS Decimal(18, 0)), 2018, N'Dizel, Otomatik')
