INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (1, N'Audi')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (2, N'Renault')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (3, N'Volkswagen')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (4, N'Fiat')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (5, N'BMW')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (6, N'Mercedes')
